django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mkfri/', include('mkfri.urls')),
    path('sns/', include('sns.urls')),
]

mkfri/urls.py
from django.conf.urls import url
# from .views import HelloView
from django.urls import path
from . import views
urlpatterns = [
  path('', views.index, name = "index"),
  path('<int:num>', views.index, name = "index"),
  path('create', views.create, name ="create"),
  path('create/<int:num>', views.edit, name='edit'),
  path('delete/<int:num>', views.delete, name='delete'),
  path('message/', views.message, name='message'),
  path('message/<int:page>', views.message, name='message'),

]

sns/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('<int:page>', views.index, name='index'),
  path('groups', views.groups, name='groups'),
  path('add', views.add, name='add'),
  path('creategroup', views.creategroup, name='creategroup'),
  path('post', views.post, name='post'),
  path('share/<int:share_id>', views.share, name='share'),
  path('good/<int:good_id>', views.good, name='good'),
]

mkfri/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
  name = models.CharField(max_length=100)
  mail = models.EmailField(max_length=200)
  gender = models.BooleanField()
  age = models.IntegerField(default=0)
  birthday = models.DateField()

  def __str__(self):
    return '<Friend:id=' + str(self.id) + ',' + self.name + '(' + str(self.age) + ')>'

class Message(models.Model):
  friend = models.ForeignKey(Friend, on_delete=models.CASCADE) #Friendモデルとの紐付け
  title = models.CharField(max_length=100)
  content = models.CharField(max_length=300)
  put_date = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return '<Message:id=' + str(self.id) + ',' + self.title + '(' + str(self.put_date) + ')>'
  
  class Meta:
    ordering = ('put_date',)

mkfri/forms.py
from django import forms
from .models import Friend, Message
class HelloForm(forms.Form):
  name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class':'form-control'}))
  mail = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class':'form-control'}))
  gender = forms.BooleanField(label='Gender', required=False, widget=forms.CheckboxInput(attrs={'class':'form-check'}))
  age = forms.IntegerField(label='Age', widget=forms.NumberInput(attrs={'class':'form-control'}))
  birthday = forms.DateField(label='Birthday', widget=forms.DateInput(attrs={'class':'form-control'}))
  

class FriendForm(forms.ModelForm):
  class Meta:
    model = Friend
    fields = ['name', 'mail', 'gender', 'age', 'birthday']

class FindForm(forms.Form):
  find = forms.CharField(label='Find', required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

class MessageForm(forms.ModelForm):
  class Meta:
    model = Message
    fields = ['title', 'content', 'friend']
    widgets ={
      'title': forms.TextInput(attrs={'class':'form-control form-control-sm'}),
      'content': forms.Textarea(attrs={'class':'form-control form-control-sm','rows':2}),
      'friend': forms.Select(attrs={'class':'form-control form-control-sm'}),
    }

mkfri/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.core.paginator import Paginator
from .forms import FriendForm,HelloForm,FindForm,MessageForm
from .models import Friend , Message

# Create your views here.

# class HelloView(TemplateView):

#   def __init__(self):
#     self.params = {
#       'title' : 'mkfri/index',
#       'msg' : 'あなたの情報を入力してください。',
#       'form' : HelloForm(),
#     }

#   def get(self, request):
#     return render(request, 'mkfri/index.html', self.params)

#   def post(self, request):
#     self.params['msg'] = '名前:' + request.POST['name'] + '<br>メール:' + request.POST['mail'] + '<br>年齢:' + request.POST['age']
#     self.params['form'] = HelloForm(request.POST)
#     return render(request, 'mkfri/index.html', self.params)
  


def index(request, num = 1):
  if (request.method == 'POST'):
    form = FindForm(request.POST)
    find = request.POST['find']
    data = Friend.objects.filter(name__icontains=find)
    page = Paginator(data, 5)
    msg = '検索結果数は' + str(data.count())
  else:
    msg = '友達の名前で検索するよ。'
    form = FindForm()
    data = Friend.objects.all()
    page = Paginator(data, 5)
  params = {
    'title' : 'hello my friends',
    'msg' : msg,
    'data' : page.get_page(num),
    'form' : form, 
  }
  return render(request, 'mkfri/index.html', params)
   

def create(request):
  if (request.method == 'POST'):
    obj = Friend()
    friend = FriendForm(request.POST, instance = obj)
    friend.save()
    return redirect(to='/mkfri')
  params = {
    'title':'Hello',
    'form':FriendForm(),
  }
  return render(request, 'mkfri/create.html', params)


def edit(request, num):
  obj = Friend.objects.get(id = num)
  if (request.method == 'POST'):
    friend = FriendForm(request.POST, instance=obj)
    friend.save()
    return redirect(to='/mkfri')
  params ={
    'title' : '友達の編集',
    'id' : num,
    'form' : FriendForm(instance=obj),
  }
  return render(request, 'mkfri/edit.html', params)

def delete(request,num):
  friend = Friend.objects.get(id=num)
  if (request.method == 'POST'):
    friend.delete()
    return redirect(to='/mkfri')
  params ={
    'title' : '友達のデータを消去する',
    'msg' : '本当に良いですか？',
    'id' : num,
    'obj' : friend
  } 
  return render(request, 'mkfri/delete.html', params)

def message(request, page=1):
  if (request.method == 'POST'):
    obj = Message()
    form = MessageForm(request.POST,instance=obj)
    form.save()
  data = Message.objects.all().reverse()
  paginator = Paginator(data,5)
  params = {
    'title': 'Message一覧',
    'form': MessageForm(),
    'data': paginator.get_page(page),
  }
  return render(request, 'mkfri/message.html', params)

mkfri/templates/mkfri/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">


  <head>
    <meta charset="utf-8">
    <title>make friends</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mkfri/css/style.css' %}">
  </head>


  <body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p><a href="{% url 'index' %}">友人一覧</a></p>
    <p><a href="{% url 'create' %}">友人作成</a></p>
    <p><a href="{% url 'message' %}">message一覧</a></p>
    <form action="{% url 'create' %}" method="post">
      {% csrf_token %}
      <table class="table">
        {{ form.as_table }}
        <tr><th><td>        
          <input type="submit" class="btn btn-primary my-2" value="送信">    
        </td></th></tr>
      </table>
    </form>
  </body>
</html>

mkfri/templates/mkfri/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">


  <head>
    <meta charset="utf-8">
    <title>make friends</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mkfri/css/style.css' %}">
  </head>


  <body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p><a href="{% url 'index' %}">友人一覧</a></p>
    <p><a href="{% url 'create' %}">友人作成</a></p>
    <p><a href="{% url 'message' %}">message一覧</a></p>
    <p>※以下のレコードを削除します。</p>
    <p class="h5 mt-4">{{msg|safe}}</p>
    
    <table class="table">
      <tr>
        <th>ID</th><td>{{obj.id}}</td>
      </tr>

      <tr>
        <th>NAME</th><td>{{obj.name}}</td>
      </tr>
      
      <tr>
        <th>GENDER</th><td>{% if obj.gender == False %}女性{% endif %}
          {% if obj.gender == True %}男性{% endif %}</td>
      </tr>

      <tr>
        <th>MAIL</th><td>{{obj.mail}}</td>
      </tr>

      <tr>
        <th>AGE</th><td>{{obj.age}}</td>
      </tr>

      <tr>
        <th>BIRTHDAY</th><td>{{obj.birthday}}</td>
      </tr>
  
      <form action="{% url 'delete' id %}" method="post">
        {% csrf_token %}
        <tr><th></th><td>  
        <input type="submit" class="btn btn-primary my-2" value="削除">
        </td>
      </tr>
      
    </table>
  </body>


</html>

mkfri/templates/mkfri/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">


  <head>
    <meta charset="utf-8">
    <title>make friends</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mkfri/css/style.css' %}">
  </head>


  <body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p><a href="{% url 'index' %}">友人一覧</a></p>
    <p><a href="{% url 'create' %}">友人作成</a></p>
    <p><a href="{% url 'message' %}">message一覧</a></p>
    <form action="{% url 'edit' id %}" method="post">
      {% csrf_token %}
      <table class="table">
        {{ form.as_table }}
        <tr><th><td>        
          <input type="submit" class="btn btn-primary my-2" value="送信">    
        </td></th></tr>
      </table>
    </form>
  </body>
</html>

mkfri/templates/mkfri/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">


  <head>
    <meta charset="utf-8">
    <title>make friends</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mkfri/css/style.css' %}">
  </head>


  <body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p class="h5 mt-4">{{msg|safe}}</p>
    <form action="{% url 'index' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <tr><th><td>        
        <input type="submit" class="btn btn-primary my-2" value="検索">    
      </td></th></tr>
    </form>
    <p><a href="{% url 'index' %}">友人一覧</a></p>
    <p><a href="{% url 'create' %}">友人作成</a></p>
    <p><a href="{% url 'message' %}">message一覧</a></p>
    
    
    <table class="table">
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>GENDER</th>
        <th>MAIL</th>
        <th>AGE</th>
        <th>BIRTHDAY</th>
        <th>修正</th>
        <th>削除</th>
        <th>メッセージ</th>
      </tr>
      {% for item in data %}
      <tr>
        <td>{{item.id}}</td>
        <td>{{item.name}}</td>
        <td>{% if item.gender == False %}女性{% endif %}
            {% if item.gender == True %}男性{% endif %}</td>
        <td>{{item.mail}}</td>
        <td>{{item.age}}</td>
        <td>{{item.birthday}}</td>
        <td><a href="{% url 'edit' item.id %}">Edit</a></td>
        <td><a href="{% url 'delete' item.id %}">Delete</a></td>
        <td><ul>{% for ob in item.message_set.all %}
                      <li>{{ob.title}}</li>
                {% endfor %}
        </ul></td>
      </tr>
      {% endfor %}
    </table>
    <ul class="pagination">
      {% if data.has_previous %}
      <li class="page-item"><a href=" {% url 'index' %}" class="page-link">&laquo; first</a></li>
      <li class="page-item"><a href=" {% url 'index' %}{{data.previous_page_number}}" class="page-link">&laquo; prev</a></li>
      {% else %}
      <li class="page-item"><a class="page-link">&laquo; first</a></li>
      <li class="page-item"><a class="page-link">&laquo; prev</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a></li>
      {% if data.has_next %}
      <li class="page-item"><a href=" {% url 'index' %}{{data.next_page_number}}" class="page-link">next &raquo;</a></li>
      <li class="page-item"><a href=" {% url 'index' %}{{data.paginator.num_pages}}" class="page-link">last &raquo;</a></li>
      {% else %}
      <li class="page-item"><a class="page-link">next &raquo;</a></li>
      <li class="page-item"><a class="page-link">last &raquo;</a></li>
      {% endif %}
    </ul>
  </body>


</html>

mkfri/templates/mkfri/message.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">


  <head>
    <meta charset="utf-8">
    <title>make friends</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mkfri/css/style.css' %}">
  </head>


  <body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <form action="{% url 'message' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}   
      <input type="submit" class="btn btn-primary my-2" value="検索">    
    </form>
    <p><a href="{% url 'index' %}">友人一覧</a></p>
    <p><a href="{% url 'create' %}">友人作成</a></p>
    <p><a href="{% url 'message' %}">message一覧</a></p>
    <table class="table">
      <tr>
        <th class="py-1">title</th>
        <th class="py-1">name</th>
        <th class="py-1">datetime</th>
      </tr>
      {% for item in data %}
      <tr>
        <td class="py-2">{{item.title}}</td>
        <td class="py-2">{{item.friend.name}}</td>
        <td class="py-2">{{item.put_date}}</td>
      </tr>
      {% endfor %}
    </table>
    
    
    
    <ul class="pagination">
      {% if data.has_previous %}
      <li class="page-item"><a href=" {% url 'message' %}" class="page-link">&laquo; first</a></li>
      <li class="page-item"><a href=" {% url 'message' %}{{data.previous_page_number}}" class="page-link">&laquo; prev</a></li>
      {% else %}
      <li class="page-item"><a class="page-link">&laquo; first</a></li>
      <li class="page-item"><a class="page-link">&laquo; prev</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a></li>
      {% if data.has_next %}
      <li class="page-item"><a href=" {% url 'message' %}{{data.next_page_number}}" class="page-link">next &raquo;</a></li>
      <li class="page-item"><a href=" {% url 'message' %}{{data.paginator.num_pages}}" class="page-link">last &raquo;</a></li>
      {% else %}
      <li class="page-item"><a class="page-link">next &raquo;</a></li>
      <li class="page-item"><a class="page-link">last &raquo;</a></li>
      {% endif %}
    </ul>
  </body>


</html>